name: myapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.3.1"
  firebase_database: "^0.1.2"
  validator: ">=0.0.4 <0.1.0"
  facebook_sign_in:
    git: https://github.com/bramvbilsen/Flutter-Facebook-Sign-In-Plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - mainframe_assets/profile/displayPhoto.jpg
    - mainframe_assets/profile/profilePhoto.jpg
    - mainframe_assets/images/m7x5ba.jpg
    - mainframe_assets/images/Mainframe_Dance_System_Logo.png
    - mainframe_assets/images/powered_by_2x.png
    - mainframe_assets/images/button_mds.png
    - mainframe_assets/images/add_button.png
    - mainframe_assets/images/add_highlight.png
    - mainframe_assets/images/age_modal_btn.png
    - mainframe_assets/images/level_row_divider.png
    - mainframe_assets/images/sel_age_bg.png
    - mainframe_assets/images/attended_before@2x.png
  # icons
    - mainframe_assets/icons/noun_939113_cc@2x.png
    - mainframe_assets/icons/noun_961889_cc@2x.png
    - mainframe_assets/icons/noun_1037967_cc@2x.png
    - mainframe_assets/icons/noun_1042992_cc@2x.png
    - mainframe_assets/icons/noun_1049935_cc@2x.png
    - mainframe_assets/icons/noun_1098180_cc@2x.png
    - mainframe_assets/icons/noun_1129072_cc@2x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat-Light
       fonts:
         - asset: fonts/Montserrat-Light.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Montserrat-Medium
       fonts:
         - asset: fonts/Montserrat-Medium.otf
     - family: Montserrat-Regular
       fonts:
         - asset: fonts/Montserrat-Regular.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
